import {
  ArrowUp,
  MoreHorizontal,
  Moon,
  Sun,
  Bolt,
  BookOpen,
  Brain,
  Briefcase,
  ChevronDown,
  ChevronRight,
  Clock,
  Code,
  Code2,
  Copyright,
  Cpu,
  Database,
  ExternalLink,
  Facebook,
  Gem,
  Github,
  GitBranch,
  GraduationCap,
  Heart,
  Home,
  Info,
  Laptop,
  Leaf,
  Link2,
  Linkedin,
  Loader2,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessagesSquare,
  Microchip,
  MousePointer2,
  Network,
  Palette,
  Phone,
  Plug,
  Quote,
  Rocket,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  Sparkles,
  Star,
  Terminal,
  Type,
  FileText,
  User,
  Waves,
  X,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const icons = {
  home: Home,
  user: User,
  star: Star,
  briefcase: Briefcase,
  cpu: Cpu,
  microchip: Microchip,
  graduationCap: GraduationCap,
  messages: MessagesSquare,
  mail: Mail,
  phone: Phone,
  whatsapp: MessageCircle,
  mapPin: MapPin,
  clock: Clock,
  send: Send,
  info: Info,
  loader: Loader2,
  github: Github,
  linkedin: Linkedin,
  facebook: Facebook,
  externalLink: ExternalLink,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  code: Code,
  link: Link2,
  settings: Settings,
  share: Share2,
  heart: Heart,
  copyright: Copyright,
  quote: Quote,
  arrowUp: ArrowUp,
  more: MoreHorizontal,
  menu: Menu,
  x: X,
  sun: Sun,
  moon: Moon,
  rocket: Rocket,
  laptop: Laptop,
  server: Server,
  database: Database,
  palette: Palette,
  shield: Shield,
  plug: Plug,
  brain: Brain,
  terminal: Terminal,
  sitemap: Network,
  network: Network,
  gitBranch: GitBranch,
  leaf: Leaf,
  git: Github,
  bolt: Bolt,
  react: Code2,
  typescript: Type,
  text: Type,
  fileText: FileText,
  node: Server,
  gem: Gem,
  waves: Waves,
  sparkles: Sparkles,
  mouse: MousePointer2,
  docker: Server,
  book: BookOpen,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

type IconProps = {
  name: IconName;
  className?: string;
  size?: number;
};

export function Icon({ name, className, size = 18 }: IconProps) {
  const LucideIcon = icons[name];
  return <LucideIcon className={cn("shrink-0", className)} size={size} aria-hidden />;
}
